name: my_app_jm_2
description: "Um novo projeto Flutter"
publish_to: 'none'  # Remove para publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0  # Versão do Dart SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Ícones no estilo iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Boas práticas de código

flutter:
  uses-material-design: true  # Habilita ícones do Material Design
  
  assets:
    - assets/jm_profile.jpeg  # Sua imagem de perfil

  fonts:
    - family: Pacifico  # Fonte 1
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400  # Peso normal
    - family: SourcePro  # Fonte 2
      fonts:
        - asset: fonts/SourceCodePro-VariableFont_wght.ttf
          weight: 400  # Peso normal